# Generated by Django 2.1.5 on 2019-02-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20190213_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='votes_total',
        ),
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
